services:
  dc-bot:
    build: .
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 8000
    ports:
      - "28000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
